---
version: '3'
services:
  openhands-app:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.20.0
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=custom-runtime
      - LOG_ALL_EVENTS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.openhands-state:/.openhands-state
    ports:
      - "3001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
